name: Build and deploy Vue.js app to VPS

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -x
            echo "Début du déploiement"
            # Vérifier et ajuster les permissions du répertoire parent
            echo "Changement de propriétaire et permissions"
            sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /var/www/TrackersStats
            sudo chmod -R 775 /var/www/TrackersStats

            # Créer le répertoire de destination s'il n'existe pas
            echo "Vérification du répertoire"
            if [ ! -d /var/www/TrackersStats ]; then
              echo "Clonage du dépôt"
              git clone git@github.com:DocCreeps/TrackersStats.git /var/www/TrackersStats
            fi

            cd /var/www/TrackersStats

            # Réinitialiser les modifications locales
            echo "Réinitialisation et mise à jour du dépôt"
            git reset --hard origin/master

            # Mettre à jour le dépôt
            git pull origin master

            # Installer les dépendances Node.js
            echo "Installation des dépendances"
            if [ -f package.json ]; then
              npm install
            else
              echo "Le fichier package.json n'existe pas."
              exit 1
            fi

            # Construire l'application Vue.js
            echo "Construction de l'application"
            npm run build
            echo "Contenu du répertoire dist:"
            ls -l dist

            # Copier les fichiers construits vers le répertoire de déploiement
            echo "Copie des fichiers"
            if [ -d dist ]; then
              rm -rf dist/* # Supprimez le contenu existant
            fi
            cp -r dist/. /var/www/TrackersStats/
            # Copier le fichier .htaccess
            if [ -f .htaccess ]; then
                cp .htaccess /var/www/TrackersStats/
            fi

            # Créer le fichier .env
            echo "Création du fichier .env"
            echo "API_KEY=${{ secrets.API_KEY }}" >> /var/www/TrackersStats/.env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> /var/www/TrackersStats/.env

            echo "Contenu du répertoire de déploiement:"
            ls -l /var/www/TrackersStats/
            
            echo "Construction de l'application"
            npm run build
            echo "Déploiement réussi"
          EOF
