name: Build and deploy Vue.js app to VPS

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            
            # Vérifier et ajuster les permissions du répertoire parent
            sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /var/www/TrackersStats 
            sudo chmod -R 775 /var/www/TrackersStats

            # Créer le répertoire de destination s'il n'existe pas
            if [ ! -d /var/www/TrackersStats ]; then
                git clone git@github.com:DocCreeps/TrackersStats.git /var/www/TrackersStats
            fi
          
            echo "Current directory: $(pwd)"
            cd /var/www/TrackersStats
            echo "Current directory: $(pwd)"
          
          # Créer un répertoire temporaire pour la sauvegarde dans /var/www/
               TEMP_DIR=/var/www/temp_backup
               mkdir -p $TEMP_DIR

          # Sauvegarder le fichier .env dans le répertoire temporaire
               if [ -f .env ]; then
               cp .env $TEMP_DIR/.env.backup
               fi

          # Réinitialiser les modifications locales
               git reset --hard origin/master

          # Mettre à jour le dépôt
               git pull origin master

          # Restaurer le fichier .env depuis le répertoire temporaire
               if [ -f $TEMP_DIR/.env.backup ]; then
               cp $TEMP_DIR/.env.backup .env
               fi

          # Supprimer le répertoire temporaire
               rm -rf $TEMP_DIR
          
          
            # Installer les dépendances Node.js
            if [ -f package.json ]; then
                npm install
            else
                echo "Le fichier package.json n'existe pas."
                exit 1
            fi

            # Construire l'application Vue.js
            npm run build

            # Copier les fichiers construits vers le répertoire de déploiement
            rm -rf /var/www/TrackersStats/dist/* # Supprimez le contenu existant
            cp -r /var/www/TrackersStats/dist/* /var/www/TrackersStats/

            # Définir les permissions appropriées pour www-data
            chown -R www-data:www-data /var/www/TrackersStats

            echo "Deployment successful"
          EOF
